name: Publicación
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint:typescript && npm run lint:sass

      - name: Upload to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build:storybook

      - name: Build
        run: |
          npm run build:typescript
          npm run build:sass
          npm run build:docs

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .storybook-out

      - name: Release
        run: npm run release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}